name: Reflex_deploy

on: 
  push:
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest

    permissions: 
      contents: write

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3' 
          cache: 'pip'
        
      - name: dependences
        run: pip install -r ./link_bio/requirements.txt
        
      - name: export frontend
        run: cd link_bio && reflex export --frontend-only
        
      - name: unzip frontend
        run: unzip link_bio/frontend.zip -d link_bio/public

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: update page
