name: Reflex_deploy

on: 
  push:
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu

    permissions: 
      contents: write

    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3' 
          cache: 'pip'
      - name: directory
        run: cd link_bio
        
      - name: dependences
        run: pip install -r requirements.txt
        
      - name: export frontend
        run: reflex export --frontend-only
        
      - name: unzip frontend
        run: unzip frontend.zip -d public

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: update page
